/*
 * UAVCAN data structure definition for libcanard.
 *
 * Autogenerated, do not edit.
 *
 */

#ifndef __AUTOMATION_DIGITALVALUES
#define __AUTOMATION_DIGITALVALUES

#include <stdint.h>
#include "canard.h"

#ifdef __cplusplus
extern "C"
{
#endif

/******************************* Source text **********************************
# Shoud be dynamic array but dynamic bool arrays compilation is broken.
# see: https://github.com/UAVCAN/libcanard/issues/135
# 32+6 bits fit into one packet for all contexts it is used in
uint6 values_len
bool[32] values
******************************************************************************/

/********************* DSDL signature source definition ***********************
automation.DigitalValues
saturated uint6 values_len
saturated bool[32] values
******************************************************************************/

#define AUTOMATION_DIGITALVALUES_NAME                      "automation.DigitalValues"
#define AUTOMATION_DIGITALVALUES_SIGNATURE                 (0xE02C971A9499EC08ULL)

#define AUTOMATION_DIGITALVALUES_MAX_SIZE                  ((38 + 7)/8)

// Constants

#define AUTOMATION_DIGITALVALUES_VALUES_LENGTH                                           32

typedef struct
{
    // FieldTypes
    uint8_t    values_len;                    // bit len 6
    bool       values[32];                    // Static Array 1bit[32] max items

} automation_DigitalValues;

extern
uint32_t automation_DigitalValues_encode(automation_DigitalValues* source, void* msg_buf);

extern
int32_t automation_DigitalValues_decode(const CanardRxTransfer* transfer, uint16_t payload_len, automation_DigitalValues* dest, uint8_t** dyn_arr_buf);

extern
uint32_t automation_DigitalValues_encode_internal(automation_DigitalValues* source, void* msg_buf, uint32_t offset, uint8_t root_item);

extern
int32_t automation_DigitalValues_decode_internal(const CanardRxTransfer* transfer, uint16_t payload_len, automation_DigitalValues* dest, uint8_t** dyn_arr_buf, int32_t offset);

#ifdef __cplusplus
} // extern "C"
#endif
#endif // __AUTOMATION_DIGITALVALUES