/*
 * UAVCAN data structure definition for libcanard.
 *
 * Autogenerated, do not edit.
 *
 */

#ifndef __AUTOMATION_VALUES
#define __AUTOMATION_VALUES

#include <stdint.h>
#include "canard.h"

#ifdef __cplusplus
extern "C"
{
#endif

#include <automation/AnalogValues.h>
#include <automation/DigitalValues.h>

/******************************* Source text **********************************
@union
DigitalValues digital_values
AnalogValues analog_values
******************************************************************************/

/********************* DSDL signature source definition ***********************
automation.Values
@union
automation.DigitalValues digital_values
automation.AnalogValues analog_values
******************************************************************************/

#define AUTOMATION_VALUES_NAME                             "automation.Values"
#define AUTOMATION_VALUES_SIGNATURE                        (0x508F04A46E815A46ULL)

#define AUTOMATION_VALUES_MAX_SIZE                         ((39 + 7)/8)

// Constants

typedef enum
{
    AUTOMATION_VALUES_DIGITAL_VALUES,
    AUTOMATION_VALUES_ANALOG_VALUES
} automation_Values_ENUM;

typedef struct
{
    automation_Values_ENUM union_tag;        // union_tag indicates what field the data structure is holding

    union
    {
    // FieldTypes
    automation_DigitalValues digital_values;                //
    automation_AnalogValues analog_values;                 //

    };
} automation_Values;

extern
uint32_t automation_Values_encode(automation_Values* source, void* msg_buf);

extern
int32_t automation_Values_decode(const CanardRxTransfer* transfer, uint16_t payload_len, automation_Values* dest, uint8_t** dyn_arr_buf);

extern
uint32_t automation_Values_encode_internal(automation_Values* source, void* msg_buf, uint32_t offset, uint8_t root_item);

extern
int32_t automation_Values_decode_internal(const CanardRxTransfer* transfer, uint16_t payload_len, automation_Values* dest, uint8_t** dyn_arr_buf, int32_t offset);

#ifdef __cplusplus
} // extern "C"
#endif
#endif // __AUTOMATION_VALUES